FROM riscv64/ubuntu:22.04

RUN apt-get update -y
RUN apt-get install -y autoconf automake autotools-dev curl python3 python3-pip python3-tomli libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev libslirp-dev
RUN apt-get install -y qemu-system-riscv64 gdb-multiarch

COPY .bash_history /root/.bash_history
COPY .inputrc /root/.inputrc

CMD ["/bin/bash"]
